enum ConfigEnum {
  NODE_ENV = 'NODE_ENV',
  JWT_SECRET = 'JWT_SECRET',
  DATABASE_URL = 'DATABASE_URL',
  REDIS_PORT = 'REDIS_PORT',
  REDIS_HOST = 'REDIS_HOST',
  REDIS_USERNAME = 'REDIS_USERNAME',
  REDIS_PASSWORD = 'REDIS_PASSWORD',
}

export default ConfigEnum;
